# Generated by Django 6.0 on 2026-01-24 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_options_alter_posts_options_and_more'),
        ('profiles', '0003_hobby_userhobby_userprofile_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='profiles.hobby'),
        ),
    ]
