# Generated by Django 6.0 on 2026-01-24 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_category'),
        ('profiles', '0003_hobby_userhobby_userprofile_hobbies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la quedada')),
                ('description', models.TextField(verbose_name='Descripción del plan')),
                ('location', models.CharField(max_length=255, verbose_name='Lugar de encuentro')),
                ('event_date', models.DateTimeField(verbose_name='Fecha y hora del evento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_participants', models.PositiveIntegerField(default=10, verbose_name='Número máximo de asistentes')),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='profiles.hobby')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='events_attending', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quedada',
                'verbose_name_plural': 'Quedadas',
                'ordering': ['event_date'],
            },
        ),
    ]
