# Generated by Django 6.0 on 2026-02-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('expert', 'Experto')], default='beginner', max_length=20, verbose_name='Nivel de la actividad'),
        ),
    ]
