# Generated by Django 6.0 on 2026-02-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_event_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('all', ' Para todos'), ('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('expert', 'Experto')], default='beginner', max_length=20, verbose_name='Nivel de la actividad'),
        ),
    ]
