# Generated by Django 6.0 on 2026-06-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_event_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='¿Es un evento online?'),
        ),
        migrations.AddField(
            model_name='event',
            name='stream_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace de transmisión (YouTube, etc.)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar de encuentro'),
        ),
    ]
