# Generated by Django 6.0 on 2026-06-07 15:57

from django.db import migrations


def migrate_participants(apps, schema_editor):
    Event = apps.get_model('posts', 'Event')
    EventAttendance = apps.get_model('posts', 'EventAttendance')

    for event in Event.objects.all():
        # Si el evento es online, todos los actuales son online. Si no, son presenciales.
        attendance_type = 'online' if event.is_online and not event.location else 'physical'
        
        # Iterar sobre los asistentes usando el M2M manager existente
        for user in event.participants.all():
            EventAttendance.objects.get_or_create(
                event=event,
                user=user,
                defaults={'attendance_type': attendance_type}
            )

def reverse_migrate_participants(apps, schema_editor):
    # Si hacemos rollback, simplemente borramos todo lo de EventAttendance.
    EventAttendance = apps.get_model('posts', 'EventAttendance')
    EventAttendance.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_eventattendance'),
    ]

    operations = [
        migrations.RunPython(migrate_participants, reverse_migrate_participants),
    ]
