# Generated by Django 6.0 on 2026-06-07 17:40

import django.core.validators
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='video',
            field=models.FileField(blank=True, help_text='Formatos soportados: MP4, MOV, AVI, WEBM. Tamaño máximo: 20MB', null=True, upload_to='posts_videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm']), posts.models.validate_video_size], verbose_name='vídeo'),
        ),
        migrations.AddField(
            model_name='posts',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enlace a YouTube, Vimeo, etc.', max_length=500, null=True, verbose_name='enlace de vídeo'),
        ),
    ]
