# Generated by Django 6.0 on 2026-06-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_posts_video_posts_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcomment',
            options={'ordering': ['-created_at']},
        ),
    ]
