# Generated by Django 6.0 on 2026-06-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_eventcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'comentario', 'verbose_name_plural': 'comentarios'},
        ),
    ]
