# Generated by Django 6.0 on 2026-06-15 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_event_image'),
        ('profiles', '0006_userprofile_address_userprofile_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='profiles.hobby', verbose_name='Categoría'),
        ),
    ]
