# Generated by Django 6.0 on 2026-08-28 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_hidden_by'),
        ('posts', '0020_event_deleted_at_event_is_active_posts_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='chat_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_linked', to='chat.conversation', verbose_name='Grupo de Chat'),
        ),
    ]
