# Generated by Django 6.0 on 2026-09-03 09:46

import django.core.validators
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_event_chat_group'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name='posts',
                    old_name='video_url',
                    new_name='external_url',
                ),
                migrations.AlterField(
                    model_name='posts',
                    name='external_url',
                    field=models.URLField(blank=True, db_column='video_url', help_text='Enlace a una web, vídeo (YouTube, Vimeo), artículo externo o recurso', max_length=500, null=True, verbose_name='enlace de interés'),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='posts',
            name='document',
            field=models.FileField(blank=True, help_text='Formato soportado: PDF. Tamaño máximo: 10MB', null=True, upload_to='posts_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), posts.models.validate_document_size], verbose_name='documento adjunto (PDF)'),
        ),
    ]
