# Generated by Django 6.0 on 2026-02-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
