# Generated by Django 6.0 on 2026-06-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_hobby_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección de la consulta', max_length=255, null=True, verbose_name='dirección'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, help_text='Móvil de contacto', max_length=20, null=True, verbose_name='teléfono móvil'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Teléfono de la consulta', max_length=20, null=True, verbose_name='teléfono fijo'),
        ),
    ]
