# Generated by Django 6.0 on 2026-06-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_address_userprofile_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='numero_socio',
            field=models.CharField(blank=True, help_text='Número de socio de la asociación', max_length=50, null=True, verbose_name='número de socio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Nombre de la empresa o autónomo', max_length=255, null=True, verbose_name='razón social'),
        ),
    ]
