# Generated by Django 6.0 on 2026-07-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_userprofile_numero_socio_userprofile_razon_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Cuéntanos sobre ti (máx. 3250 caracteres)', max_length=3250, null=True, verbose_name='biografía'),
        ),
    ]
