version: '3.8'

services:
  web:
    build: .
    restart: always
    env_file:
      - .env.prod
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - redis
      - db

  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password_seguro}
      MYSQL_DATABASE: ${DB_NAME:-aficionados_network_db}
      MYSQL_USER: ${DB_USER:-django_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-tu_password_seguro}
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    restart: always
    # No exponemos el puerto hacia el host por seguridad, la red interna de docker lo maneja.

  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  db_data:
