INSERT INTO profiles_hobby (name, description, slug) VALUES
('Quiromasaje', 'Terapia natural', 'Quiromasaje'),
('Masaje tradicional tailandeś', 'Terapia natural', 'Masaje tradicional tailandeś'),
('Masaje miofascial', 'Terapia natural', 'Masaje miofascial'),
('Amasaje Ayurveda', 'Terapia natural', 'Amasaje Ayurveda'),
('Masaje Abdominal', 'Terapia natural', 'Masaje Abdominal'),
('Masaje tántrico', 'Terapia natural', 'Masaje tántrico'),
('Acupuntura tradicional china', 'Terapia natural', 'Acupuntura tradicional china'),
('Acupuntura Tung', 'Terapia natural', 'Acupuntura Tung'),
('Acupuntura Japonesa', 'Terapia natural', 'Acupuntura Japonesa'),
('Acupuntura Toyohari', 'Terapia natural', 'Acupuntura Toyohari'),
('Acupuntura Coreana', 'Terapia natural', 'Acupuntura Coreana'),
('Manupuntura Coreana', 'Terapia natural', 'Manupuntura Coreana'),
('Acupuntura Distal', 'Terapia natural', 'Acupuntura Distal'),
('Acupuntura de Meridianos', 'Terapia natural', 'Acupuntura de Meridianos'),
('Acupuntura Craneal', 'Terapia natural', 'Acupuntura Craneal'),
('Acupuntura de Manos y tobillos', 'Terapia natural', 'Acupuntura de Manos y tobillos'),
('Acupuntura de Ombligo', 'Terapia natural', 'Acupuntura de Ombligo'),
('Terapia con Ventosas', 'Terapia natural', 'Terapia con Ventosas'),
('Moxibustión china', 'Terapia natural', 'Moxibustión china'),
('Okyu', 'Terapia natural', 'Okyu'),
('Ontake', 'Terapia natural', 'Ontake'),
('Homeopatía', 'Terapia natural', 'Homeopatía'),
('Flores de Bach', 'Terapia natural', 'Flores de Bach'),
('Kinesiología', 'Terapia natural', 'Kinesiología'),
('Reiky', 'Terapia natural', 'Reiky'),
('Programación Neurolingüística (PNL)', 'Terapia natural', 'Programación Neurolingüística (PNL)'),
('Terapia Avatar', 'Terapia natural', 'Terapia Avatar'),
('Osteopatía', 'Terapia natural', 'Osteopatía'),
('Terapia Craneosacral/Sacrocraneal', 'Terapia natural', 'Terapia Craneosacral/Sacrocraneal'),
('Masaje Ayurveda', 'Terapia natural', 'Masaje Ayurveda');