# Generated by Django 6.0 on 2026-06-12 12:29

import django.core.validators
import django.db.models.deletion
import posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0006_userprofile_address_userprofile_mobile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(max_length=2000, verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Pon 0 para intercambios o si es a convenir.', max_digits=10, verbose_name='precio')),
                ('listing_type', models.CharField(choices=[('SALE', 'Venta'), ('RENT', 'Alquiler de equipo'), ('SPACE', 'Alquiler de Espacio/Gabinete'), ('EXCHANGE', 'Intercambio'), ('OTHER', 'Otro')], default='SALE', max_length=20, verbose_name='tipo de anuncio')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RESERVED', 'Reservado'), ('SOLD', 'Vendido/Alquilado')], default='AVAILABLE', max_length=20, verbose_name='estado')),
                ('image', models.ImageField(blank=True, help_text='Formatos soportados: JPG, JPEG, PNG. Tamaño máximo: 5MB', null=True, upload_to='marketplace_images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), posts.models.validate_image_size], verbose_name='imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de publicación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('hobby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='profiles.hobby', verbose_name='terapia')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='vendedor')),
            ],
            options={
                'verbose_name': 'anuncio',
                'verbose_name_plural': 'anuncios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='puntuación')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de valoración')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_left', to=settings.AUTH_USER_MODEL, verbose_name='comprador/evaluador')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_reviews', to=settings.AUTH_USER_MODEL, verbose_name='vendedor')),
            ],
            options={
                'verbose_name': 'valoración de vendedor',
                'verbose_name_plural': 'valoraciones de vendedores',
                'ordering': ['-created_at'],
                'unique_together': {('seller', 'reviewer')},
            },
        ),
    ]
