# Generated by Django 6.0 on 2026-06-12 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('profiles', '0006_userprofile_address_userprofile_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='hobby',
            field=models.ForeignKey(blank=True, help_text='Déjalo en blanco si el artículo/servicio aplica a múltiples terapias (ej: una camilla).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='profiles.hobby', verbose_name='terapia'),
        ),
    ]
