# Generated by Django 6.0 on 2026-06-15 10:11

import django.core.validators
import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_listing_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='video',
            field=models.FileField(blank=True, help_text='Opcional. Duración máxima: 1 minuto. Tamaño máximo: 15MB. Formatos: MP4, WebM, MOV.', null=True, upload_to='marketplace_videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov']), marketplace.models.validate_video_size], verbose_name='video'),
        ),
    ]
