# Generated by Django 6.0 on 2026-01-24 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_notification_comment_and_more'),
        ('posts', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.event', verbose_name='Quedada'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Seguimiento'), ('like', 'Me gusta'), ('comment', 'Comentario'), ('event', 'Quedada')], max_length=20, verbose_name='Tipo de notificación'),
        ),
    ]
