# Generated by Django 6.0 on 2026-01-25 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_event_and_more'),
        ('profiles', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.review', verbose_name='Valoración'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Seguimiento'), ('like', 'Me gusta'), ('comment', 'Comentario'), ('event', 'Quedada'), ('review', 'Valoración')], max_length=20, verbose_name='Tipo de notificación'),
        ),
    ]
