# Generated by Django 6.0 on 2026-06-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mensaje de sistema/logro'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Seguimiento'), ('like', 'Me gusta'), ('comment', 'Comentario'), ('event', 'Quedada'), ('review', 'Valoración'), ('badge', 'Logro Obtenido')], max_length=20, verbose_name='Tipo de notificación'),
        ),
    ]
