# Generated by Django 6.0 on 2026-06-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Seguimiento'), ('like', 'Me gusta'), ('comment', 'Comentario'), ('event', 'Quedada'), ('review', 'Valoración'), ('badge', 'Logro Obtenido'), ('article_comment', 'Comentario en Artículo'), ('article_rating', 'Valoración de Artículo')], max_length=20, verbose_name='Tipo de notificación'),
        ),
    ]
